on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        name: Set up Node.js
        with:
          node-version: 14
      - name: Build and Test
        run: |
          npm ci
          npm run build
