on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Build code
        runs:
          using: 'docker'
          image: 'Dockerfile'

